# examples/client.py
#
# Minimal HTTPS client that POSTs a jitter score to the example server.
# Demonstrates mTLS client-certificate usage with the test CA generated by
# scripts/make-certs.sh.
#
# Usage:
#   1. Generate test certificates (from the repo root):
#        bash scripts/make-certs.sh
#   2. Start the server in another terminal:
#        python examples/server.py
#   3. Install dependencies:
#        pip install "requests>=2.28"
#   4. Run the client:
#        python examples/client.py [score]
#
#      e.g.  python examples/client.py 3.14
#
# The client trusts the local test CA and presents the client certificate so
# that mutual TLS (mTLS) works when the server has mTLS enabled.
#
# SPDX-License-Identifier: MIT (same as repository root)

from __future__ import annotations

import sys
from pathlib import Path

import requests

# ---------------------------------------------------------------------------
# Certificate paths (relative to the repo root)
# ---------------------------------------------------------------------------
_REPO_ROOT = Path(__file__).resolve().parent.parent
_CERT_DIR = _REPO_ROOT / "certs"
_CA_CERT = _CERT_DIR / "ca.crt"         # trust anchor for the server certificate
_CLIENT_PEM = _CERT_DIR / "client.pem"  # combined client cert + key for mTLS

_URL = "https://localhost:8443/jitter"

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    # Accept an optional score from the command line; default to 2.5.
    score: float
    if len(sys.argv) > 1:
        try:
            score = float(sys.argv[1])
        except ValueError:
            print(f"Usage: python {sys.argv[0]} [score]", file=sys.stderr)
            sys.exit(1)
    else:
        score = 2.5

    for path in (_CA_CERT, _CLIENT_PEM):
        if not path.exists():
            print(
                f"Certificate file not found: {path}\n"
                "Run 'bash scripts/make-certs.sh' first.",
                file=sys.stderr,
            )
            sys.exit(1)

    payload = {"score": score}
    print(f"POST {_URL}  payload={payload}")

    response = requests.post(
        _URL,
        json=payload,
        # Trust the local test CA instead of the system bundle.
        verify=str(_CA_CERT),
        # Present the client certificate for mutual TLS (mTLS).
        # Remove 'cert' if the server does not require client certificates.
        cert=str(_CLIENT_PEM),
        timeout=10,
    )

    print(f"Status : {response.status_code}")
    print(f"Body   : {response.text}")


if __name__ == "__main__":
    main()
