#!/usr/bin/env python3
"""
examples/updater.py – Secure auto-updater prototype for jitterbugs.

WARNING: DO NOT USE THIS AS A PRODUCTION UPDATE MECHANISM; FOR DEMO/TESTING ONLY.

Demonstrates:
  - Fetching a signed manifest over HTTPS
  - Verifying the manifest signature with an embedded RSA public key
  - Downloading an artifact and verifying its SHA-256 checksum
  - Atomic install via temp-file + os.replace() swap
  - Keeping a backup of the previous version for rollback
  - Structured logging to examples/updater.log
  - CLI flags: --check-only, --manifest-url, --sig-url, --verify,
                --auto, --version-file

Usage (see examples/README_UPDATER.md for full walkthrough):
  python examples/updater.py --check-only
  python examples/updater.py --auto
  python examples/updater.py --manifest-url https://localhost:8443/updates/manifest.json \\
                              --sig-url     https://localhost:8443/updates/manifest.json.sig \\
                              --verify      certs/ca.crt \\
                              --auto

Requirements: requests>=2.28, cryptography>=3.4
"""

import argparse
import base64
import hashlib
import json
import logging
import os
import shutil
import sys
import tempfile
from pathlib import Path

import requests
from cryptography.exceptions import InvalidSignature
from cryptography.hazmat.primitives import hashes, serialization
from cryptography.hazmat.primitives.asymmetric import padding

# ---------------------------------------------------------------------------
# Embedded test public key (RSA-2048, generated by scripts/make-update-keys.sh)
# Replace this PEM with your actual public key before using even for testing.
# In production use a secure key-management solution – NOT a hardcoded key.
# ---------------------------------------------------------------------------
EMBEDDED_PUBLIC_KEY_PEM = b"""\
-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0Z3VS5JJcds3xHn/ygWe
rMY6FiqBGrFzgJuPVjmqXqZ2CLYP53Pyi6ISqzYIYGt8T/FjhIjSIcP11aw9RJU6
Hhq5v/FbMqjzgQ6DI7gDWI/Gejp/xGEZBBEGEEtHUNTkuIY+iqRLrEgr5qNcDhbU
bkF+ZTm2QXUFfxdBwPSLgRCKDwkiPdNKDRsMDPYNbWj3MfB4RRWkU31D/WoGY4Wl
jSBMRJIXS7p8YHMO6TY0o1B7HBXG+sF0kBIaKb8O5L+4EagMjBqDBKm+kzNJ8YfI
5RMhxmAZsFnMUhSyN8H7TPQF/Gjg+8W/5Ywp8LQS5FZj+3v+yz7bMbRQ0MXIHQID
AQAB
-----END PUBLIC KEY-----
"""

# ---------------------------------------------------------------------------
# Defaults
# ---------------------------------------------------------------------------
DEFAULT_MANIFEST_URL = "https://localhost:8443/updates/manifest.json"
DEFAULT_SIG_URL = "https://localhost:8443/updates/manifest.json.sig"
DEFAULT_VERIFY = "certs/ca.crt"  # path to CA bundle; set to True for system CAs
DEFAULT_VERSION_FILE = os.path.join(os.path.dirname(__file__), ".version")
DEFAULT_INSTALL_DIR = os.path.join(os.path.dirname(__file__), "current")
DEFAULT_BACKUP_DIR = os.path.join(os.path.dirname(__file__), "backup")
DEFAULT_LOG_FILE = os.path.join(os.path.dirname(__file__), "updater.log")


# ---------------------------------------------------------------------------
# Logging setup
# ---------------------------------------------------------------------------
def setup_logging(log_file: str) -> logging.Logger:
    """Configure file + console logging."""
    logger = logging.getLogger("updater")
    logger.setLevel(logging.DEBUG)
    fmt = logging.Formatter("%(asctime)s [%(levelname)s] %(message)s")

    fh = logging.FileHandler(log_file)
    fh.setFormatter(fmt)
    logger.addHandler(fh)

    ch = logging.StreamHandler(sys.stdout)
    ch.setFormatter(fmt)
    logger.addHandler(ch)

    return logger


# ---------------------------------------------------------------------------
# Network helpers
# ---------------------------------------------------------------------------
def fetch_bytes(url: str, verify) -> bytes:
    """Fetch *url* over HTTPS and return raw bytes.

    *verify* accepts the same values as requests' verify parameter:
      True  – use system CA bundle
      False – skip verification (insecure; only for ad-hoc testing)
      str   – path to a CA bundle or CA cert file
    """
    resp = requests.get(url, timeout=30, verify=verify)
    resp.raise_for_status()
    return resp.content


# ---------------------------------------------------------------------------
# Signature verification
# ---------------------------------------------------------------------------
def verify_manifest_signature(
    manifest_bytes: bytes,
    sig_bytes: bytes,
    public_key_pem: bytes,
) -> bool:
    """Verify an RSA-PKCS1v15/SHA-256 signature over *manifest_bytes*.

    *sig_bytes* must be the raw (DER) signature bytes; if your server
    produces a base64 file, decode it first with base64.b64decode().

    Returns True on success, raises InvalidSignature on failure.
    """
    pub_key = serialization.load_pem_public_key(public_key_pem)
    pub_key.verify(
        sig_bytes,
        manifest_bytes,
        padding.PKCS1v15(),
        hashes.SHA256(),
    )
    return True


# ---------------------------------------------------------------------------
# Checksum
# ---------------------------------------------------------------------------
def sha256_of(data: bytes) -> str:
    """Return the hex-encoded SHA-256 digest of *data*."""
    return hashlib.sha256(data).hexdigest()


# ---------------------------------------------------------------------------
# Version helpers
# ---------------------------------------------------------------------------
def read_local_version(version_file: str) -> str:
    """Return the locally installed version string, or '0' if unknown."""
    try:
        return Path(version_file).read_text().strip()
    except FileNotFoundError:
        return "0"


def is_newer(remote: str, local: str) -> bool:
    """Naïve lexicographic comparison – replace with semver if needed."""
    return remote > local


# ---------------------------------------------------------------------------
# Atomic install + rollback
# ---------------------------------------------------------------------------
def atomic_install(artifact_bytes: bytes, filename: str, install_dir: str,
                   backup_dir: str, logger: logging.Logger) -> bool:
    """Install *artifact_bytes* atomically under *install_dir*.

    Steps:
      1. Write to a temp file in the same directory.
      2. Move the current installed file to *backup_dir* (rollback copy).
      3. Atomically rename temp → destination.
      4. On any error after backup, attempt rollback.

    Returns True on success, False on failure (rollback attempted).
    """
    os.makedirs(install_dir, exist_ok=True)
    os.makedirs(backup_dir, exist_ok=True)

    dest = os.path.join(install_dir, filename)
    backup = os.path.join(backup_dir, filename)

    # Write to temp file in the same filesystem to allow atomic rename
    tmp_fd, tmp_path = tempfile.mkstemp(dir=install_dir, prefix=".tmp_")
    try:
        with os.fdopen(tmp_fd, "wb") as f:
            f.write(artifact_bytes)
        logger.info("Artifact written to temp file: %s", tmp_path)

        # Keep a backup of the previous version for rollback
        if os.path.exists(dest):
            shutil.copy2(dest, backup)
            logger.info("Previous version backed up to: %s", backup)

        # Atomic swap
        os.replace(tmp_path, dest)
        logger.info("Artifact installed atomically to: %s", dest)
        return True

    except Exception as exc:  # noqa: BLE001
        logger.error("Install failed: %s", exc)
        # Attempt rollback
        if os.path.exists(backup):
            try:
                shutil.copy2(backup, dest)
                logger.info("Rollback succeeded: restored %s from backup", dest)
            except Exception as rb_exc:  # noqa: BLE001
                logger.error("Rollback also failed: %s", rb_exc)
        # Clean up temp file if it still exists
        if os.path.exists(tmp_path):
            os.unlink(tmp_path)
        return False


# ---------------------------------------------------------------------------
# Main update flow
# ---------------------------------------------------------------------------
def run_update(
    manifest_url: str,
    sig_url: str,
    verify,
    version_file: str,
    check_only: bool,
    auto: bool,
    logger: logging.Logger,
) -> int:
    """Orchestrate the full update check (and optional install).

    Returns 0 on success / no update needed, 1 on error.
    """
    logger.info("=== jitterbugs updater starting ===")
    logger.info("Manifest URL : %s", manifest_url)
    logger.info("Signature URL: %s", sig_url)
    logger.info("TLS verify   : %s", verify)

    # 1. Fetch manifest + signature -----------------------------------------
    try:
        logger.info("Fetching manifest …")
        manifest_bytes = fetch_bytes(manifest_url, verify)
        logger.info("Fetching signature …")
        sig_b64 = fetch_bytes(sig_url, verify)
    except requests.RequestException as exc:
        logger.error("Network error while fetching manifest/signature: %s", exc)
        return 1

    # 2. Decode base64 signature --------------------------------------------
    try:
        sig_bytes = base64.b64decode(sig_b64)
    except Exception as exc:  # noqa: BLE001
        logger.error("Failed to decode signature (expected base64): %s", exc)
        return 1

    # 3. Verify signature ---------------------------------------------------
    logger.info("Verifying manifest signature …")
    try:
        verify_manifest_signature(manifest_bytes, sig_bytes, EMBEDDED_PUBLIC_KEY_PEM)
        logger.info("Manifest signature OK.")
    except InvalidSignature:
        logger.error("Manifest signature INVALID – aborting update.")
        return 1
    except Exception as exc:  # noqa: BLE001
        logger.error("Signature verification error: %s", exc)
        return 1

    # 4. Parse manifest -----------------------------------------------------
    try:
        manifest = json.loads(manifest_bytes)
    except json.JSONDecodeError as exc:
        logger.error("Failed to parse manifest JSON: %s", exc)
        return 1

    remote_version = manifest.get("version", "0")
    local_version = read_local_version(version_file)
    logger.info("Local version : %s", local_version)
    logger.info("Remote version: %s", remote_version)

    if not is_newer(remote_version, local_version):
        logger.info("Already up-to-date (local=%s, remote=%s).", local_version, remote_version)
        return 0

    logger.info("Update available: %s → %s", local_version, remote_version)

    if check_only:
        logger.info("--check-only mode: not installing.")
        return 0

    if not auto:
        # Interactive prompt when neither --check-only nor --auto is set
        answer = input(
            f"Install update {local_version} → {remote_version}? [y/N] "
        ).strip().lower()
        if answer not in ("y", "yes"):
            logger.info("Update declined by user.")
            return 0

    # 5. Download and verify each file in the manifest ----------------------
    files = manifest.get("files", [])
    if not files:
        logger.error("Manifest contains no files to download.")
        return 1

    for file_info in files:
        filename = file_info.get("filename")
        url = file_info.get("url")
        expected_sha256 = file_info.get("sha256", "")

        if not filename or not url:
            logger.error("Manifest file entry missing 'filename' or 'url'.")
            return 1

        logger.info("Downloading artifact: %s from %s", filename, url)
        try:
            artifact_bytes = fetch_bytes(url, verify)
        except requests.RequestException as exc:
            logger.error("Failed to download artifact: %s", exc)
            return 1

        # 6. SHA-256 checksum verification ----------------------------------
        actual_sha256 = sha256_of(artifact_bytes)
        if expected_sha256 and actual_sha256 != expected_sha256:
            logger.error(
                "SHA-256 mismatch for %s: expected %s, got %s",
                filename, expected_sha256, actual_sha256,
            )
            return 1
        logger.info("SHA-256 checksum OK for %s.", filename)

        # 7. Atomic install -------------------------------------------------
        install_dir = DEFAULT_INSTALL_DIR
        backup_dir = DEFAULT_BACKUP_DIR
        ok = atomic_install(artifact_bytes, filename, install_dir, backup_dir, logger)
        if not ok:
            logger.error("Atomic install failed for %s.", filename)
            return 1

    # 8. Update local version file ------------------------------------------
    try:
        Path(version_file).write_text(remote_version + "\n")
        logger.info("Version file updated to %s.", remote_version)
    except OSError as exc:
        logger.warning("Could not update version file: %s", exc)

    logger.info("=== Update complete: %s → %s ===", local_version, remote_version)
    return 0


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------
def parse_args(argv=None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "jitterbugs auto-updater prototype. "
            "DO NOT USE AS PRODUCTION UPDATE MECHANISM."
        )
    )
    parser.add_argument(
        "--manifest-url",
        default=DEFAULT_MANIFEST_URL,
        help="HTTPS URL of the signed manifest (default: %(default)s)",
    )
    parser.add_argument(
        "--sig-url",
        default=DEFAULT_SIG_URL,
        help="HTTPS URL of the manifest base64 signature file (default: %(default)s)",
    )
    parser.add_argument(
        "--verify",
        default=DEFAULT_VERIFY,
        help=(
            "TLS verification: path to CA bundle, 'true' (system CAs), "
            "or 'false' (disable – INSECURE). Default: %(default)s"
        ),
    )
    parser.add_argument(
        "--version-file",
        default=DEFAULT_VERSION_FILE,
        help="Path to local version file (default: %(default)s)",
    )
    parser.add_argument(
        "--check-only",
        action="store_true",
        help="Only check for updates; do not download or install",
    )
    parser.add_argument(
        "--auto",
        action="store_true",
        help="Download and install automatically without prompting",
    )
    return parser.parse_args(argv)


def _coerce_verify(value: str):
    """Convert CLI --verify string to a value suitable for requests."""
    lower = value.lower()
    if lower == "true":
        return True
    if lower == "false":
        return False
    return value  # treat as file path


def main(argv=None) -> int:
    args = parse_args(argv)
    logger = setup_logging(DEFAULT_LOG_FILE)
    verify = _coerce_verify(str(args.verify))
    return run_update(
        manifest_url=args.manifest_url,
        sig_url=args.sig_url,
        verify=verify,
        version_file=args.version_file,
        check_only=args.check_only,
        auto=args.auto,
        logger=logger,
    )


if __name__ == "__main__":
    sys.exit(main())
